[package]
name = "rust-gen-callgraph"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.74", features = ["parsing", "full", "extra-traits"]}
dot = "0.1.4"
